source 'https://rubygems.org'

gem 'rails', '3.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem "activerecord", "~> 3.2.6"
gem 'rest-client'
gem 'state_machine'
gem 'activeldap'
gem 'net-ldap'
gem "rack", "~> 1.4.1"
# gem 'thrift', '0.9.0.1.patched'
# gem 'rcov', '0.9.11'
# gem 'acts-as-tree-with-dotted-ids'

group :test, :ci do
  gem 'test-unit'
  gem 'mocha'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'factory_girl'
end


platforms :ruby do
  gem 'thin'
  gem 'mysql2'
  gem 'yajl-ruby', '1.1.0'
end

platforms :jruby do
  gem 'activerecord-jdbcmysql-adapter'
  gem 'jruby-openssl', '0.7.6.1.patched'
  gem 'trinidad'
  gem 'jruby-rack', '1.1.4'
  gem 'json', '1.7.3'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
