test:
  adapter: <%= RUBY_PLATFORM == 'java' ? 'mysql' : 'mysql2' %>
  database: oms_test
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: <%= RUBY_PLATFORM == 'java' ? 'mysql' : 'mysql2' %>
  database: oms_test
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000